version: "3.7"
services:
  app:
    build:
      args:
        user: summy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: url-min
    container_name: url-min-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - url-min

  db:
    image: mysql:5.7
    container_name: url-min-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: url-min-db
      MYSQL_ROOT_PASSWORD: url-min
      MYSQL_PASSWORD: url-min
      MYSQL_USER: url-min
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - url-min

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8003:80
    networks:
      - url-min

  nginx:
    image: nginx:alpine
    container_name: url-min-nginx
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - url-min

networks:
  url-min:
    driver: bridge
